export const RAMP = [
  "#e8f0ff",
  "#cfe0ff",
  "#b7d0ff",
  "#9fc0ff",
  "#86afff",
  "#6f9fff",
  "#5186ff",
];

export const QUAL = [
  "#8dd3c7",
  "#ffffb3",
  "#bebada",
  "#fb8072",
  "#80b1d3",
  "#fdb462",
  "#b3de69",
  "#fccde5",
  "#d9d9d9",
  "#bc80bd",
  "#ccebc5",
  "#ffed6f",
];

export const SLUG_FIX: Record<string, string> = {
  "bayan-olgii": "bayan-ulgii",
  "govi-altay": "govi-altai",
  hovsgol: "khuvsgul",
  uvurhangai: "uvurkhangai",
  suhbaatar: "sukhbaatar",
  "darhan-uul": "darkhan-uul",
  "tuv-aimag": "tuv",
  bayanhongor: "bayankhongor",
  "orkhon-aimag": "orkhon",
  "ulaanbaatar-hot": "ulaanbaatar",
  arhangay: "arkhangai",
  dzavhan: "zavkhan",
  hentiy: "khentii",
  omnogovi: "umnugovi",
  ovorhangay: "uvurkhangai",
  tov: "tuv",
  "bayan-olgiy": "bayan-ulgii",
  hovd: "khovd",
};

export const MN_NAME_BY_SLUG: Record<string, string> = {
  arkhangai: "Архангай",
  "bayan-ulgii": "Баян-Өлгий",
  bayankhongor: "Баянхонгор",
  bulgan: "Булган",
  "darkhan-uul": "Дархан-Уул",
  dornogovi: "Дорноговь",
  dornod: "Дорнод",
  dundgovi: "Дундговь",
  "govi-altai": "Говь-Алтай",
  govisumber: "Говьсүмбэр",
  khentii: "Хэнтий",
  khovd: "Ховд",
  khuvsgul: "Хөвсгөл",
  orkhon: "Орхон",
  umnugovi: "Өмнөговь",
  omnogovi: "Өмнөговь",
  uvurkhangai: "Өвөрхангай",
  selenge: "Сэлэнгэ",
  sukhbaatar: "Сүхбаатар",
  tuv: "Төв",
  ulaanbaatar: "Улаанбаатар",
  uvs: "Увс",
  zavkhan: "Завхан",
};
